version: '3.9'

services:

  postgres:
    image: postgres:16.4
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  test-postgres:
    image: postgres:16.4
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 9432:5432
  # jubobe:
  #   image: jubobe:latest
  #   ports:
  #     - 9090:9090
  #   depends_on:
  #     - postgres
  #     - migrate

  # migrate:
  #   image: jubobe:latest
  #   command: [ "pgmigration", "migrate" ]
  #   depends_on:
  #     - postgres
