// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Shoyo",
            "url": "https://github.com/shoyo10/jubobe"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/orders": {
            "post": {
                "description": "create a order",
                "parameters": [
                    {
                        "description": "order fields",
                        "name": "reqBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.createOrderReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "order id",
                        "schema": {
                            "$ref": "#/definitions/http.createOrderResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/orders/{id}": {
            "get": {
                "description": "get a order",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "order id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.getOrderResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPError"
                        }
                    }
                }
            },
            "put": {
                "description": "update a order",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "order id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "update order fields",
                        "name": "reqBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.updateOrderReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errors.HTTPError"
                        }
                    }
                }
            }
        },
        "/api/patients": {
            "get": {
                "description": "list all patients",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.listPatientsResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "errors.HTTPError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {}
            }
        },
        "http.createOrderReq": {
            "type": "object",
            "properties": {
                "Message": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "PatientId": {
                    "type": "integer",
                    "minimum": 1
                }
            }
        },
        "http.createOrderResp": {
            "type": "object",
            "properties": {
                "Data": {
                    "$ref": "#/definitions/http.createOrderRespData"
                }
            }
        },
        "http.createOrderRespData": {
            "type": "object",
            "properties": {
                "Id": {
                    "type": "integer"
                }
            }
        },
        "http.getOrderResp": {
            "type": "object",
            "properties": {
                "Data": {
                    "$ref": "#/definitions/http.getOrderRespData"
                }
            }
        },
        "http.getOrderRespData": {
            "type": "object",
            "properties": {
                "CreatedAt": {
                    "type": "string"
                },
                "Id": {
                    "type": "integer"
                },
                "Message": {
                    "type": "string"
                },
                "PatientId": {
                    "type": "integer"
                },
                "UpdatedAt": {
                    "type": "string"
                }
            }
        },
        "http.listPatientsResp": {
            "type": "object",
            "properties": {
                "Data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.listPatientsRespData"
                    }
                }
            }
        },
        "http.listPatientsRespData": {
            "type": "object",
            "properties": {
                "Id": {
                    "type": "integer"
                },
                "Name": {
                    "type": "string"
                },
                "OrderId": {
                    "type": "integer"
                }
            }
        },
        "http.updateOrderReq": {
            "type": "object",
            "properties": {
                "Message": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9090",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Jubobe API Document",
	Description:      "This is jubo backend api document.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
